export enum TypeKeys {
    INITIALIZE_MODAL_REQUESTED = 'INITIALIZE_MODAL_REQUESTED',
    INITIALIZE_MODAL_COMPLETED = 'INITIALIZE_MODAL_COMPLETED',
    SET_MODAL_STATE = 'SET_MODAL_STATE',
    GO_TO_FORM_INFO = 'GO_TO_FORM_INFO',
    SET_VIEW_INFO_ERROR = 'SET_VIEW_INFO_ERROR',
    SET_VIEW_INFO_HEIGHT = 'SET_VIEW_INFO_HEIGHT',
    PREPARE_TO_PAY = 'PREPARE_TO_PAY',
    PREPARE_TO_RETRY = 'PREPARE_TO_RETRY',
    FORGET_PAYMENT_ATTEMPT = 'FORGET_PAYMENT_ATTEMPT',
    SET_MODAL_INTERACTION_POLLING = 'SET_MODAL_INTERACTION_POLLING'
}
