name: Master
on:
    push:
        branches:
            - 'master'
            - 'main'
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  submodules: recursive
            - name: Init
              uses: ./.github/actions/init
            - name: Build
              run: npm run build
            - name: Deploy image
              uses: valitydev/action-deploy-docker@v1.0.16
              with:
                  registry-username: ${{ github.actor }}
                  registry-access-token: ${{ secrets.GITHUB_TOKEN }}
                  dockerfile-path: .
              env:
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            - name: Create Sentry release
              uses: getsentry/action-release@v1
              env:
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
                  SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
                  SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
              with:
                  environment: 'production'
                  sourcemaps: './dist'
