name: Master
on:
    push:
        branches:
            - 'master'
            - 'main'
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  submodules: recursive
            - name: Init
              uses: ./.github/actions/init
            - name: Build
              run: npm run build
              env:
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
                  SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
                  SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
            - name: Deploy image
              uses: valitydev/action-deploy-docker@v2
              with:
                  registry-username: ${{ github.actor }}
                  registry-access-token: ${{ secrets.GITHUB_TOKEN }}
            - name: set config
              run: |
                  printf "$APP_ENV_FILE" > dist/v1/appConfig.json
              shell: bash
              env:
                  APP_ENV_FILE: ${{secrets.APP_CONFIG_CF}}
            - name: Publish to CF Pages
              uses: cloudflare/pages-action@1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  projectName: 'payform'
                  directory: 'dist'
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
                  branch: main
            - name: set v2 config
              run: |
                  printf "$APP_2_ENV_FILE" > dist/v1/appConfig.json
              shell: bash
              env:
                  APP_2_ENV_FILE: ${{secrets.APP_2_CONFIG_CF}}
            - name: Publish 2 to CF Pages
              uses: cloudflare/pages-action@1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  projectName: 'payform-2'
                  directory: 'dist'
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
                  branch: main
            - name: set v3 config
              run: |
                  printf "$APP_3_ENV_FILE" > dist/v1/appConfig.json
              shell: bash
              env:
                  APP_3_ENV_FILE: ${{secrets.APP_3_CONFIG_CF}}
            - name: Publish v3 to CF Pages
              uses: cloudflare/pages-action@1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  projectName: 'payform-globalgatein'
                  directory: 'dist'
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
                  branch: main
            - name: set v4 config
              run: |
                  printf "$APP_4_ENV_FILE" > dist/v1/appConfig.json
              shell: bash
              env:
                  APP_4_ENV_FILE: ${{secrets.APP_4_CONFIG_CF}}
            - name: Publish v4 to CF Pages
              uses: cloudflare/pages-action@1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  projectName: 'payform-flow3dtunnel'
                  directory: 'dist'
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
                  branch: main
            - name: set v5 config
              run: |
                  printf "$APP_5_ENV_FILE" > dist/v1/appConfig.json
              shell: bash
              env:
                  APP_5_ENV_FILE: ${{secrets.APP_5_CONFIG_CF}}
            - name: Publish v5 to CF Pages
              uses: cloudflare/pages-action@1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  projectName: 'payform-v5'
                  directory: 'dist'
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
                  branch: main
