name: PR
on: [pull_request]
jobs:
    init:
        name: Init
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Init
              uses: ./.github/actions/init
            - name: Cache
              uses: actions/cache@v3
              id: cache
              with:
                  path: ./*
                  key: ${{ github.sha }}
    lint-format-check:
        name: Lint and prettier check
        runs-on: ubuntu-latest
        needs: [init]
        steps:
            - name: Cache
              uses: actions/cache@v3
              id: cache
              with:
                  path: ./*
                  key: ${{ github.sha }}
            - name: Lint
              run: npm run lint
            - name: Prettier
              run: npm run prettier
    test:
        name: Test
        runs-on: ubuntu-latest
        needs: [init]
        steps:
            - name: Cache
              uses: actions/cache@v3
              id: cache
              with:
                  path: ./*
                  key: ${{ github.sha }}
            - name: Test
              run: npm run test
    build:
        name: Build
        runs-on: ubuntu-latest
        needs: [init]
        steps:
            - name: Cache
              uses: actions/cache@v3
              id: cache
              with:
                  path: ./*
                  key: ${{ github.sha }}
            - name: Build
              run: npm run build
            - name: set config
              run: |
                  printf "$APP_ENV_FILE" > dist/v1/appConfig.json
              shell: bash
              env:
                  APP_ENV_FILE: ${{secrets.APP_CONFIG_CF}}
            - name: Publish to CF Pages
              uses: cloudflare/pages-action@1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  projectName: 'checkout'
                  directory: 'dist'
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}