name: PR
on: [pull_request]
jobs:
    init:
        name: Init
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Init
              uses: ./.github/actions/init
            - name: Cache
              uses: actions/cache@v3
              id: cache
              with:
                  path: ./*
                  key: ${{ github.sha }}
    check:
        name: Check
        runs-on: ubuntu-latest
        needs: [init]
        steps:
            - name: Cache
              uses: actions/cache@v3
              id: cache
              with:
                  path: ./*
                  key: ${{ github.sha }}
            - name: Init NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: '16.13.2'
                  cache: 'npm'
            - name: Check
              run: npm run check
            - name: Run tests
              run: npm run test
    build:
        name: Build
        runs-on: ubuntu-latest
        needs: [init]
        steps:
            - name: Cache
              uses: actions/cache@v3
              id: cache
              with:
                  path: ./*
                  key: ${{ github.sha }}
            - name: Init NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: '16.13.2'
                  cache: 'npm'
            - name: Build
              run: npm run build
